version: '3'
services:

  postgres:
    image: postgres:14.3
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fastapi_db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
