version: '3'
services:

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8081:8000
    volumes:
      - ./:/usr/src/notes:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432


  postgres:
    image: postgres:14.3
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fastapi_db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
