version: '3'
services:

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8081:8000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fastapi_user
      - DB_PASSWORD=secret
      - DB_NAME=fastapi_db
      - SECRET_KEY=02a25912d44e1a24e219620715c3d3730931fd0f607a459beaeab68d6fa0f82c
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - SPELLER_URL=https://speller.yandex.net/services/spellservice.json/checkText
      - LANGUAGES=ru,en
      - WAIT_HOSTS=postgres:5432


  postgres:
    image: postgres:14.3
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fastapi_db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
